# Site settings
title: "Thought flash"
author: susansecret
author_avatar: https://s.gravatar.com/avatar/d3cb9edccfd931c38acb6fefcd8f2ffd?s=80
email: zxl1218yaya@gmail.com
description: Blog about whatever.
baseurl: "" # optional
url: "https://susansecret.github.io"
#twitter_username: susansecret
#github_username: susansecret
github_repo: susansecret/susansecret.github.io
#google_analytics: UA-80085-YOUR-ID
# disqus: disqus-id

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap
